export const ROUTES = {
  LOGIN: '/login',
  SESSION_EXPIRED: '/session-expired',
  DASHBOARD: '/dashboard',

  MY_PROJECTS: '/workspace/my-projects',
  RELEASES: '/workspace/releases',
  TEST_CASES: '/workspace/test-cases',
  DEFECTS: '/workspace/defects',
  REPORTS: '/workspace/reports',

  PROJECTS: '/project-management/projects',
  PROJECT_CREATE: '/project-management/projects/create',
  PROJECT_EDIT: '/project-management/projects/:projectId/edit',
  BENCH_AVAILABLE_EMPLOYEES: '/bench/available-employees',
  BENCH_PROJECT_ALLOCATION: '/bench/project-allocation',
  MODULES: '/project-management/modules',
  ALLOCATION_HISTORY: '/project-management/allocation-history',
  PROJECT_WORKSPACE: '/projects/:projectId',
  PROJECT_MANAGEMENT_HUB: '/projects/:projectId/project-management',
  PROJECT_OVERVIEW: '/projects/:projectId/overview',
  PROJECT_DETAILS: '/projects/:projectId/details',
  PROJECT_MODULES: '/projects/:projectId/modules',
  PROJECT_TEST_CASES: '/projects/:projectId/test-cases',
  PROJECT_RELEASE_HUB: '/projects/:projectId/release-management',
  PROJECT_RELEASES: '/projects/:projectId/releases',
  PROJECT_TEST_CASE_EXECUTION: '/projects/:projectId/releases/test-case-execution',
  PROJECT_TEST_CASE_ALLOCATION: '/projects/:projectId/releases/test-case-allocation',
  PROJECT_RELEASE_CREATE: '/projects/:projectId/releases/create',
  PROJECT_RELEASE_DETAIL: '/projects/:projectId/releases/:releaseId',
  PROJECT_RELEASE_EDIT: '/projects/:projectId/releases/:releaseId/edit',
  PROJECT_RELEASE_WORKSPACE: '/projects/:projectId/releases/:releaseId/workspace',
  PROJECT_DEFECTS: '/projects/:projectId/defects',
  PROJECT_ALLOCATION_HISTORY: '/projects/:projectId/allocation-history',
  PROJECT_REPORTS: '/projects/:projectId/reports',

  EMPLOYEES: '/user-management/employees',
  EMPLOYEE_CREATE: '/user-management/employees/create',
  EMPLOYEE_DETAIL: '/user-management/employees/:id',
  EMPLOYEE_EDIT: '/user-management/employees/:id/edit',
  ROLES: '/configuration/roles',
  ROLE_CREATE: '/configuration/roles/create',
  ROLE_DETAIL: '/configuration/roles/:id',
  ROLE_EDIT: '/configuration/roles/:id/edit',
  PRIVILEGES: '/user-management/privileges',
  DESIGNATIONS: '/configuration/designations',
  DESIGNATION_CREATE: '/configuration/designations/create',
  DESIGNATION_EDIT: '/configuration/designations/:id/edit',

  DEFECT_TYPE: '/configuration/defect-type',
  DEFECT_TYPE_CREATE: '/configuration/defect-type/create',
  DEFECT_TYPE_EDIT: '/configuration/defect-type/:id/edit',
  RELEASE_TYPE: '/configuration/release-type',
  RELEASE_TYPE_CREATE: '/configuration/release-type/create',
  RELEASE_TYPE_EDIT: '/configuration/release-type/:id/edit',
  SEVERITY: '/configuration/severity',
  SEVERITY_CREATE: '/configuration/severity/create',
  SEVERITY_EDIT: '/configuration/severity/:id/edit',
  PRIORITY: '/configuration/priority',
  PRIORITY_CREATE: '/configuration/priority/create',
  PRIORITY_EDIT: '/configuration/priority/:id/edit',
  STATUS: '/configuration/status',
  STATUS_TYPE: '/configuration/status-management/status-type',
  STATUS_TYPE_CREATE: '/configuration/status-management/status-type/create',
  STATUS_TYPE_EDIT: '/configuration/status-management/status-type/:id/edit',
  STATUS_WORKFLOW: '/configuration/status-management/status-workflow-setup',
  DEFECT_WORKFLOW: '/configuration/status-management/defect-workflow',
  DEFECT_WORKFLOW_EDIT: '/configuration/status-management/defect-workflow/edit',

  PRIVILEGE: '/configuration/privilege',
  PRIVILEGE_LIST: '/configuration/privilege-management/privileges',
  ROLE_PRIVILEGE_ASSIGNMENT: '/configuration/privilege-management/role-assignment',
  USER_PERMISSION_OVERRIDE: '/configuration/privilege-management/user-override',

  EMAIL_MANAGEMENT: '/configuration/email-management',
  EMAIL_CONFIGURATION: '/system-settings/email-configuration',
  EMAIL_POINT_SETUP: '/system-settings/email-point-setup',
} as const
